# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sonata.admin.utilisateur:
        class: Wcs\WildResaBundle\Admin\UtilisateursAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Liste des Utilisateurs", label: "Utilisateur" }
        arguments:
            - ~
            - Wcs\WildResaBundle\Entity\Utilisateurs
            - ~

    sonata.Wild.Machines:
            class: Wcs\WildResaBundle\Admin\MachinesWild
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Liste des Machines", label: "Machine" }
            arguments:
                - ~
                - Wcs\WildResaBundle\Entity\Machines
                - ~
