<?php

namespace Wcs\WildResaBundle\Entity;

/**
 * MachinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachinesRepository extends \Doctrine\ORM\EntityRepository
{
}
