<?php

namespace Wcs\WildResaBundle\Entity;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends \Doctrine\ORM\EntityRepository
{
}
